@startuml
skinparam actorStyle Hollow
(*)-> "Affiche la liste des lignes existantes dans la table" as list
if Selection d'une action
    ->[Creation] "Formulaire"

else
    -d->[Edition, suppression] "Recuperation des données de la ligne
    selectionée pour remplir le formulaire" as prerempli
endif
prerempli -> Formulaire
Formulaire ...> list
@enduml
